# /contratos-app/docker-compose.yml

version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: contratos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: contratos_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/contratos_gerados:/app/contratos_gerados
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: contratos_frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    container_name: contratos_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: